python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py &&
python3 train_random_regnet.py