DATA_PATH = f'/home/andrew/sleep/data'
EXPERIMENTS_PATH = f'/home/andrew/sleep/experiments'
TMP_EXPERIMENTS_PATH = f'./exp'
BEAST_EXPERIMENTS_PATH = f'/home/andrew/sleep/experiments_beast'
BEAUTY_EXPERIMENTS_PATH = f'/home/andrew/sleep/experiments_beauty'
DEVICE='cuda'
DATASET_PATH = f'../data/pt_ekyn'
GANDALFS_PATH = f'../models'
WINDOW_SIZE = 9